#!/bin/bash
echo "" >> ~/todo.mk
echo "########################################" >> ~/todo.mk
date >> ~/todo.mk
echo "" >> ~/todo.mk
echo "TODO:" >> ~/todo.mk
echo "" >> ~/todo.mk
echo "DONE:">> ~/todo.mk
echo "" >> ~/todo.mk
echo "NOTES:">> ~/todo.mk
echo "" >> ~/todo.mk


